/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Example API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface CreateUserInfo200Response {
    'code'?: number;
    'data'?: MainCreateUserInfoResp;
    'message'?: string;
}
export interface GetUserInfo200Response {
    'code'?: number;
    'data'?: Array<MainGetUserInfoResp>;
    'message'?: string;
}
export interface MainCreateUserInfoReq {
    'age'?: number;
    /**
     * ID   uint   `json:\"id\"`
     */
    'name'?: string;
}
export interface MainCreateUserInfoResp {
    'id'?: number;
}
export interface MainDeleteUserInfoReq {
    'id'?: number;
}
export interface MainGetUserInfoResp {
    'age'?: number;
    'id'?: number;
    'name'?: string;
}
export interface MainResponse {
    'code'?: number;
    'data'?: object;
    'message'?: string;
}
export interface MainUpdateUserInfoReq {
    'age'?: number;
    'id'?: number;
    'name'?: string;
}

/**
 * UserApi - axios parameter creator
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 創建用戶
         * @param {MainCreateUserInfoReq} request request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUserInfo: async (request: MainCreateUserInfoReq, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('createUserInfo', 'request', request)
            const localVarPath = `/user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 刪除用戶
         * @param {MainDeleteUserInfoReq} request request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteUserInfo: async (request: MainDeleteUserInfoReq, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('deleteUserInfo', 'request', request)
            const localVarPath = `/user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 取得用戶清單
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserInfo: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 修改用戶資訊
         * @param {MainUpdateUserInfoReq} request request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUserInfo: async (request: MainUpdateUserInfoReq, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('updateUserInfo', 'request', request)
            const localVarPath = `/user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 */
export const UserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 創建用戶
         * @param {MainCreateUserInfoReq} request request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createUserInfo(request: MainCreateUserInfoReq, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateUserInfo200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createUserInfo(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.createUserInfo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 刪除用戶
         * @param {MainDeleteUserInfoReq} request request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteUserInfo(request: MainDeleteUserInfoReq, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MainResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteUserInfo(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.deleteUserInfo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 取得用戶清單
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserInfo(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserInfo200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserInfo(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.getUserInfo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 修改用戶資訊
         * @param {MainUpdateUserInfoReq} request request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateUserInfo(request: MainUpdateUserInfoReq, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MainResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateUserInfo(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.updateUserInfo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserApi - factory interface
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserApiFp(configuration)
    return {
        /**
         * 
         * @summary 創建用戶
         * @param {MainCreateUserInfoReq} request request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUserInfo(request: MainCreateUserInfoReq, options?: RawAxiosRequestConfig): AxiosPromise<CreateUserInfo200Response> {
            return localVarFp.createUserInfo(request, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 刪除用戶
         * @param {MainDeleteUserInfoReq} request request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteUserInfo(request: MainDeleteUserInfoReq, options?: RawAxiosRequestConfig): AxiosPromise<MainResponse> {
            return localVarFp.deleteUserInfo(request, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 取得用戶清單
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserInfo(options?: RawAxiosRequestConfig): AxiosPromise<GetUserInfo200Response> {
            return localVarFp.getUserInfo(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 修改用戶資訊
         * @param {MainUpdateUserInfoReq} request request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUserInfo(request: MainUpdateUserInfoReq, options?: RawAxiosRequestConfig): AxiosPromise<MainResponse> {
            return localVarFp.updateUserInfo(request, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserApi - object-oriented interface
 */
export class UserApi extends BaseAPI {
    /**
     * 
     * @summary 創建用戶
     * @param {MainCreateUserInfoReq} request request body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createUserInfo(request: MainCreateUserInfoReq, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).createUserInfo(request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 刪除用戶
     * @param {MainDeleteUserInfoReq} request request body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteUserInfo(request: MainDeleteUserInfoReq, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).deleteUserInfo(request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 取得用戶清單
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getUserInfo(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).getUserInfo(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 修改用戶資訊
     * @param {MainUpdateUserInfoReq} request request body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateUserInfo(request: MainUpdateUserInfoReq, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).updateUserInfo(request, options).then((request) => request(this.axios, this.basePath));
    }
}



